### ISSUE TITLE
Github page is down

### ISSUE THREAD

**Issue by greendragon2010** [jamesmgittins/incremancer#10]
GIthub Page for this repository is down, so it is broken on Kongregate as well.

**Comment by jamesmgittins** [comment]
That's weird. Nothing had changed as far as I can tell. I pushed a commit to the readme file and it came back up again.

I have https://dopeslinger.gti.nz hosted on github as well and that didn't go down.

**Comment by greendragon2010** [comment]
I'm not sure either, and there is no documentation about pages going down due to inactivity of the repository or site.
