### ISSUE TITLE
Humans don't spawn if drag item into trash can while Level Complete screen is open

### ISSUE THREAD

**Issue by petertseng** [jamesmgittins/incremancer#11]
1. Have unequipped item in inventory.
2. Open skeleton menu and drag item over trash can (trash can should get yellow highlight).
3. Wait for Level Complete screen to show up.
4. Release item over trash can while Level Complete screen still open.

Result: Starting the next level generates no humans, and the level gets completed without any combat. This continues, allowing the player to unfairly make unimpeded progress but not being very fun without any combat.

Doesn't seem to matter whether Auto Start Next Level setting is on or off.
Doesn't seem to happen with any inventory slot, only the trash can.
You're safe if you release the item back into the inventory rather than into the trash can, so it's something very specific about the trash can that does it.

**Comment by petertseng** [comment]
Weird, I can only get this to happen on Firefox and not on Chrome. On Chrome, when the Level Complete screen comes up, the mouse is no longer considered to be hovering over the trash can, so I cannot drop the item into the trash to get this to happen. On Firefox, the mouse is still considered to be hovering over the trash can (yellow highlight still is there).

**Comment by petertseng** [comment]
I guess that's not the definition of a soft lock, I'll just rename it to humans don't spawn

**Comment by jamesmgittins** [comment]
I will test it and see if I can fix it. Firefox native drag and drop doesn't work as nicely as it does in chrome or edge for some reason.

**Comment by petertseng** [comment]
This doesn't happen anymore. I don't have speculations on what fixed it.
