### ISSUE TITLE
Collectors not showing up on https://incremancer.gti.nz/

### ISSUE THREAD

**Issue by codefreak558** [jamesmgittins/incremancer#13]
Like the title says when playing on https://incremancer.gti.nz/ the bone collectors do not show up

**Comment by codefreak558** [comment]
So far what I found that seems to fix the problem is to go into https://github.com/jamesmgittins/incremancer/deployments and load the one from the 15th of March and then it loads most if not all the files. So far while playing doing that seems to have it so that all the things that were missing have shown up

**Comment by norbby42** [comment]
I'm not able to reproduce this.  I assume you're referring to the Bone Collectors in the Graveyard?

Started a new game on [incremancer.gt.nz](https://incremancer.gti.nz/) after failing to export prior savegame from an Android device, and have both the UI controls to allocate them in the Graveyard, and I can visibly see them in the game world.

**Comment by codefreak558** [comment]
Well I found a way to get it to do what I've found was running the latest deployment it doesnt show everything

**Comment by jamesmgittins** [comment]
A lot of people have reported some sprites being invisible. I haven't been able to reproduce it on any of my devices though. It could be a specific hardware issue that doesn't like the webGL library I'm using. Possibly not enough VRAM or something, although the sprites are extremely low res, so it seems unlikely.

**Comment by codefreak558** [comment]
Ah okay it seeems that its just the latest deployment on that does it

**Comment by codefreak558** [comment]
Ah okay it seems that its just the latest deployment on that does it

**Comment by codefreak558** [comment]
For now I have gotten it working if I can get anything else to work on the newer ones then I will reopen this issue but I think for now its been solved the best I can think of
