### ISSUE TITLE
After Bottomless pit, no constructions available

### ISSUE THREAD

**Issue by ambs** [jamesmgittins/incremancer#17]
After Bottomless pit, I have no constructions available.
A friend have built other things like Hybrid Laboratory, but I do not have that option.

**Comment by ambs** [comment]
To help:
Got up to level 799
Still no pink gear for skeleton (better I got is red).
Running in firefox

**Comment by Cloudninjakip** [comment]
your friend is playing something like [https://cirusdane.github.io/incremancer/](https://cirusdane.github.io/incremancer/) which is a modified version of the game that has pink gear and hybrid laboratory

**Comment by ambs** [comment]
That's true. Thank you, @Cloudninjakip.
